//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class action報表
    {
        public int Itinerary_ID { get; set; }
        public int 行為ID { get; set; }
        public int 評分表ID { get; set; }
    
        public virtual C_Itinerary_Plan_行程計畫 C_Itinerary_Plan_行程計畫 { get; set; }
        public virtual action總表 action總表 { get; set; }
        public virtual 評分表 評分表 { get; set; }
    }
}
