//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_List
    {
        public int Bank_List1 { get; set; }
        public Nullable<int> CTBC_Bank { get; set; }
        public Nullable<int> E_SUN_Bank { get; set; }
        public Nullable<int> First_Commercial_Bank { get; set; }
        public Nullable<int> Chang_Hwa_Commercial_Bank { get; set; }
        public Nullable<int> Citibank { get; set; }
        public Nullable<int> SinoPac { get; set; }
        public Nullable<int> HSBC_Bank { get; set; }
    }
}
