//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Rentals_Info
    {
        public int Transportation_ID { get; set; }
        public string Plate_No_ { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public short Number_of_Seats { get; set; }
        public decimal Price { get; set; }
    
        public virtual Transportation_List Transportation_List { get; set; }
    }
}
