//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit_Card_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credit_Card_Company()
        {
            this.Payment_Method = new HashSet<Payment_Method>();
        }
    
        public int Credit_Card_Company_ID { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> C_Credit_Card_Category_ID { get; set; }
    
        public virtual Credit_Card_Category_List Credit_Card_Category_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Method> Payment_Method { get; set; }
    }
}
