//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Room_Types_No_ { get; set; }
        public int Equipments_List_Codes { get; set; }
        public Nullable<int> Hair_Dryer { get; set; }
        public Nullable<bool> Towel { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> Tub { get; set; }
        public Nullable<bool> Window { get; set; }
        public Nullable<bool> None_Smoking_Room { get; set; }
        public Nullable<bool> Breakfast { get; set; }
    
        public virtual Room_Type Room_Types { get; set; }
    }
}
