//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Info
    {
        public int Transportation_ID { get; set; }
        public int Flight { get; set; }
        public string Airline_Company { get; set; }
        public string Departure_Date { get; set; }
        public string Destination { get; set; }
        public System.DateTime Departure_Time { get; set; }
        public System.DateTime Time_Of_Arrival { get; set; }
        public decimal Price { get; set; }
    
        public virtual Transportation_List Transportation_List { get; set; }
    }
}
