//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelerEntities3 : DbContext
    {
        public TravelerEntities3()
            : base("name=TravelerEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member_Info_List> Member_Info_Lists { get; set; }
        public virtual DbSet<Hotel_List> Hotel_Lists { get; set; }
        public virtual DbSet<行程明細> 行程明細 { get; set; }
        public virtual DbSet<城市總表> 城市總表 { get; set; }
    }
}
