//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order訂單
    {
        public int Unified_Business_No_ { get; set; }
        public int Payment_Number { get; set; }
        public int Member_ID { get; set; }
        public Nullable<int> Price { get; set; }
        public int Payment_Methods_ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> 隨行人數 { get; set; }
        public Nullable<int> Itinerary_ID { get; set; }
    
        public virtual C_Itinerary_Plan_行程計畫 C_Itinerary_Plan_行程計畫 { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual Member_Info_List Member_Info_List { get; set; }
    }
}
