//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Railway_Info
    {
        public int Transportation_ID { get; set; }
        public int Railway_Departure { get; set; }
        public string Railway_type { get; set; }
        public string Railway_Departure_station { get; set; }
        public string Railway_Terminal_station { get; set; }
        public System.DateTime Departure_time { get; set; }
        public System.DateTime Arrival_time { get; set; }
        public decimal Price { get; set; }
    
        public virtual Transportation_List Transportation_List { get; set; }
    }
}
