//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travelling_Companion
    {
        public int Travelling_Companion_ID { get; set; }
        public int Member_ID { get; set; }
        public string Travelling_Companion_Name { get; set; }
        public string Travelling_Companion_Title { get; set; }
        public string Travelling_Companion_Phone_Number { get; set; }
        public string Travelling_Companion_Nationality { get; set; }
        public string Travelling_Companion_Passport_Number { get; set; }
        public string Travelling_Companion_Passport_Expiry_Date { get; set; }
    
        public virtual Member_Info_List Member_Info_List { get; set; }
    }
}
