//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class 付款方式總表
    {
        public int 付款方式ID { get; set; }
        public string 付款方式 { get; set; }
        public int 會員ID { get; set; }
    
        public virtual Member_Info_List Member_Info_List { get; set; }
    }
}
