//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class 景點名稱總表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 景點名稱總表()
        {
            this.景點報表ID = new HashSet<景點報表ID>();
        }
    
        public int 景點名稱ID { get; set; }
        public string 景點名稱 { get; set; }
        public int 地區ID { get; set; }
        public int 城市ID { get; set; }
    
        public virtual 地區總表 地區總表 { get; set; }
        public virtual 城市總表 城市總表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<景點報表ID> 景點報表ID { get; set; }
    }
}
