//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class 行程計畫介紹圖集
    {
        public int 行程計畫介紹圖集ID { get; set; }
        public int 行程計畫介紹ID { get; set; }
        public byte[] 圖片介紹 { get; set; }
    
        public virtual 行程計畫介紹 行程計畫介紹 { get; set; }
    }
}
