//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order訂單
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order訂單()
        {
            this.OrderDetails隨行人員 = new HashSet<OrderDetails隨行人員>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> Unified_Business_No_ { get; set; }
        public int Member_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Payment_Methods_ID { get; set; }
        public Nullable<int> Itinerary_ID { get; set; }
        public string Credit_Card_Number { get; set; }
        public int 訂單狀態編號ID { get; set; }
    
        public virtual Itinerary_Plan行程計畫 Itinerary_Plan行程計畫 { get; set; }
        public virtual Member_Info_List Member_Info_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails隨行人員> OrderDetails隨行人員 { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
        public virtual 訂單狀態編號ID 訂單狀態編號ID1 { get; set; }
    }
}
