//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transportation
    {
        public int TransportationID { get; set; }
        public int 行程明細ID { get; set; }
        public int TransportationList_ID { get; set; }
        public string 交通工具班次 { get; set; }
        public string Company_Name { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public System.DateTime Departure_Time { get; set; }
        public System.DateTime Time_of_Arrival { get; set; }
        public decimal Price { get; set; }
    
        public virtual Transportation_List Transportation_List { get; set; }
        public virtual 行程明細 行程明細 { get; set; }
    }
}
