//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Collections.Generic;
    
    public partial class 景點報表ID
    {
        public int 景點報表ID1 { get; set; }
        public int 行程明細ID { get; set; }
        public int 景點名稱ID { get; set; }
    
        public virtual 景點名稱總表 景點名稱總表 { get; set; }
        public virtual 行程明細 行程明細 { get; set; }
    }
}
