//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelerEntities3 : DbContext
    {
        public TravelerEntities3()
            : base("name=TravelerEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action報表> action報表 { get; set; }
        public virtual DbSet<action總表> action總表 { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Hotel_List> Hotel_Lists { get; set; }
        public virtual DbSet<Itinerary_Plan行程計畫> Itinerary_Plan行程計畫 { get; set; }
        public virtual DbSet<Member_Info_List> Member_Info_Lists { get; set; }
        public virtual DbSet<OrderDetails隨行人員> OrderDetails隨行人員 { get; set; }
        public virtual DbSet<Order訂單> Order訂單 { get; set; }
        public virtual DbSet<Payment_Method> Payment_Methods { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trade_Info> Trade_Infoes { get; set; }
        public virtual DbSet<Transportation> Transportations { get; set; }
        public virtual DbSet<Transportation_List> Transportation_Lists { get; set; }
        public virtual DbSet<主題類表> 主題類表 { get; set; }
        public virtual DbSet<各地區名稱總表> 各地區名稱總表 { get; set; }
        public virtual DbSet<行程明細> 行程明細 { get; set; }
        public virtual DbSet<城市總表> 城市總表 { get; set; }
        public virtual DbSet<訂單狀態編號ID> 訂單狀態編號ID { get; set; }
        public virtual DbSet<旅遊類型總表> 旅遊類型總表 { get; set; }
        public virtual DbSet<國家名稱> 國家名稱 { get; set; }
        public virtual DbSet<國家表ID> 國家表ID { get; set; }
        public virtual DbSet<景點名稱總表> 景點名稱總表 { get; set; }
        public virtual DbSet<景點報表ID> 景點報表ID { get; set; }
        public virtual DbSet<評分表> 評分表 { get; set; }
        public virtual DbSet<優惠方案> 優惠方案 { get; set; }
    }
}
