//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Info_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member_Info_List()
        {
            this.action報表 = new HashSet<action報表>();
            this.Discounts = new HashSet<Discount>();
            this.Order訂單 = new HashSet<Order訂單>();
            this.Trade_Info = new HashSet<Trade_Info>();
        }
    
        public int Member_ID { get; set; }
        public string Name { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string D_O_B { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> bonus_points { get; set; }
        public string password { get; set; }
        public string ID_number { get; set; }
        public string SEX { get; set; }
        public byte[] image { get; set; }
        public string Passport_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<action報表> action報表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order訂單> Order訂單 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trade_Info> Trade_Info { get; set; }
    }
}
