//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Collections.Generic;
    
    public partial class 國家名稱
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 國家名稱()
        {
            this.Itinerary_Plan行程計畫 = new HashSet<Itinerary_Plan行程計畫>();
        }
    
        public int 國家總表ID { get; set; }
        public string 國家名稱1 { get; set; }
        public int 各地地區名稱ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itinerary_Plan行程計畫> Itinerary_Plan行程計畫 { get; set; }
        public virtual 各地區名稱總表 各地區名稱總表 { get; set; }
    }
}
