//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 期中專題
{
    using System;
    using System.Collections.Generic;
    
    public partial class 行程明細
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 行程明細()
        {
            this.Transportations = new HashSet<Transportation>();
            this.景點報表ID = new HashSet<景點報表ID>();
        }
    
        public int 行程明細ID { get; set; }
        public int Itinerary_ID { get; set; }
        public Nullable<int> DAY { get; set; }
        public Nullable<int> Hotel_ID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Hotel_List Hotel_List { get; set; }
        public virtual Itinerary_Plan行程計畫 Itinerary_Plan行程計畫 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transportation> Transportations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<景點報表ID> 景點報表ID { get; set; }
    }
}
